### ISSUE TITLE
What font is used in example screenshots?

### ISSUE THREAD

**Issue by beatscode** [sldobri/bunker#2]
Hello. I'm curious what font you are using in the examples. Overtime I change  to a 'Next' based template the strings becoming italicized or something.

**Hard**
![60239b25-622b-4805-938e-aecbf3070797](https://user-images.githubusercontent.com/1777648/27454545-409147b6-5768-11e7-96c1-4a6b48292fa6.png)

**Electron**
![782980a1-9258-4bcf-b675-ba3e9c6fdc97](https://user-images.githubusercontent.com/1777648/27454561-516e3ff8-5768-11e7-8f9d-afca92793581.png)

**Comment by dobbbri** [comment]
I use "FiraCode-Light", "Iosevka-Light", "OperatorMono-Light", "SFMono-Light for light fonts.

or "Fira Code", "Iosevka", "Operator Mono", "SF Mono" 


my editor settings

  "editor.fontFamily": "OperatorMono-Light",
  "editor.fontSize": 17,
  "editor.lineHeight": 25,
  "editor.fontLigatures": true,

Fira Code and Iosevka has ligatures

**Comment by dobbbri** [comment]
is that!!

"editor.fontFamily": "Operator Mono",
